from django.db import models
from django.contrib.auth.models import User


class SummaryHistory(models.Model):
    """
    Stores a single summary record for a user.
    Each entry contains the original input text, the generated summary,
    and the timestamp when the summary was created.
    """
    # Link each summary to the user who created it.
    # Cascade delete ensures histories are removed if the user is deleted.
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='summaries')
    
    # The original text the user submitted.
    input_text = models.TextField()
    
    # The summarized result generated by the app.
    summary_text = models.TextField()
    
    # Timestamp automatically set when the record is created.
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        # Show first 50 characters for easy identification
        return f"{self.user.username} - {self.input_text[:50]}"
